### ISSUE TITLE
Is the project discontinued? | Le projet est-il abandonné ?

### ISSUE THREAD

**Issue by asmtilde** [Iltotore/cylang#53]

**Comment by Iltotore** [comment]
Hello.

The project isn't discontinued. I am working on the update of [another project](https://github.com/Iltotore/iron) but I planned major changes once finished.

The changes will probably require a rewrite of the project (since almost all aspects could be done better). The main goals in the future are:
- Do not use "naïve" interpreter to allow a bigger recursion depth (especially in the web editor since the recursion limit in the browser is very low)
- Use ZIO to:
  - Make a concurrency-aware interpreter (to avoid blocking on single-threaded platforms like in the browser)
  - Make a cleaner and more readable interpreter
- Use a more recent library for parsing like Parsley, Fast Parse or ZIO-Parsing since Scala Parsing Combinators inherited some design issues and slowness.

**Comment by asmtilde** [comment]
Glad that the project isn't discontinued.
